<script setup lang="ts">
import { computed,ref } from 'vue';
import { useRunStore } from '@/stores/run';
import { useDataStore } from '@/stores/data';
import { JOURNEY_QUESTS } from '@/data/journey-quests';
import { currentJourney, goalProgress, questAvailable, questReady } from '@/systems/field-journey';
defineProps<{open:boolean}>();const emit=defineEmits<{close:[]}>();const run=useRunStore(),data=useDataStore(),history=ref(false);
const main=computed(()=>currentJourney(run.data));
const entries=computed(()=>JOURNEY_QUESTS.filter(q=>history.value?!!run.data.field?.journey?.completed[q.id]:q.id===main.value?.id||(!q.main&&!!run.data.field?.journey?.accepted[q.id]&&questAvailable(run.data,q))));
function npcLabel(id:string){return data.npcs.get(id)?.name??'주민';}
function place(id:string){
 const npc=data.npcs.get(id),map=data.nodeMaps.get(data.timelines.get(run.data.timelineId)?.nodeMapId??'');
 const known=run.data.interactionWorld?.knowledge.player?.targets['npc:'+id];
 return known?(map?.nodes.find(n=>n.id===known.nodeId.split('::')[0])?.label??'여행길')+'에서 만남':map?.nodes.find(n=>n.id===npc?.homeNodeId)?.label??'아직 만나지 못함';
}
</script>
<template><div v-if="open" class="journal-backdrop" @click.self="emit('close')" @keydown.esc.stop="emit('close')"><section role="dialog" aria-modal="true" aria-label="여행 수첩"><header><h2>여행 수첩</h2><button aria-label="수첩 닫기" @click="emit('close')">×</button></header><nav><button :aria-pressed="!history" @click="history=false">할 일</button><button :aria-pressed="history" @click="history=true">마친 부탁</button></nav><article v-for="q in entries" :key="q.id"><small v-if="q.chapter">{{ q.chapter }}</small><h3>{{ q.title }}</h3><p>{{ npcLabel(run.data.field?.journey?.accepted[q.id]?(q.turnInNpcId??q.npcId):q.npcId) }} · {{ place(run.data.field?.journey?.accepted[q.id]?(q.turnInNpcId??q.npcId):q.npcId) }}</p><template v-if="!run.data.field?.journey?.completed[q.id]"><p v-if="!run.data.field?.journey?.accepted[q.id]" class="objective">먼저 말을 걸어 보자.</p><template v-else><p v-for="(goal,i) in q.goals" :key="i" class="objective" :class="{done:goalProgress(run.data,goal)>=(goal.amount??1)}">{{ goalProgress(run.data,goal)>=(goal.amount??1)?'✓':'·' }} {{ goal.label }} <b>{{ Math.min(goalProgress(run.data,goal),goal.amount??1) }}/{{ goal.amount??1 }}</b></p><p v-if="questReady(run.data,q)" class="ready">돌아가서 이야기하자.</p><details><summary>부탁 다시 읽기</summary><p>{{ q.reminder }}</p></details></template></template><p v-else class="completed">{{ q.finish }}</p></article><p v-if="!entries.length">{{ history?'아직 마친 부탁이 없다.':'이번 여정의 이야기를 마쳤다. 다른 주민들의 부탁도 들어보자.' }}</p></section></div></template>
<style scoped>.journal-backdrop{position:fixed;inset:0;z-index:955;background:#0d181dda;display:grid;place-items:center;padding:12px;color:#e5debc}.journal-backdrop section{width:min(100%,450px);max-height:88dvh;overflow:auto;box-sizing:border-box;background:#182a22;border:1px solid #68715a;border-radius:12px;padding:16px}header,nav{display:flex;align-items:center;gap:8px}header{justify-content:space-between}h2{margin:0;font-size:18px}h3{margin:5px 0;font-size:16px}button{font:inherit;min-height:40px;padding:6px 12px;border:1px solid #68715a;background:#263c30;color:#e5debc;border-radius:5px}button[aria-pressed=true]{border-color:#d9c88b}nav{margin:12px 0}nav button{flex:1}article{border-top:1px solid #68715a66;padding:16px 0}small{font-size:10px;letter-spacing:.12em;color:#ccbc82}p,details{font-size:12px;line-height:1.7;color:#afbea8;margin:6px 0}.objective{display:flex;gap:6px;color:#e5debc}.objective b{margin-left:auto;white-space:nowrap;font-weight:400}.done{color:#9eaf96}.ready{color:#dcc885}summary{cursor:pointer}.completed{color:#b8c6ad}</style>
